# Site settings
title: Andreas Poettler - concert guitarist
description: >
  Konzertgitarrist - concert guitarist
url: "http://poettler.atspace.eu"
baseurl: /
google_analytics: UA-70394167-3

sass:
  sass_dir: css
  sourcemap: never
  style:    compressed

# Build settings
markdown: kramdown

highlighter: rouge

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  events:
    output: false

exclude:
  - .idea
  - .jekyll-cache
